- name: "Set the cpu_type play fact"
  ansible.builtin.set_fact:
    cpu_type: "{{ 'amd' if amd_cpu|length > 0 else 'intel' if intel_cpu|length > 0 else 'unknown' }}"
  vars:
    intel_cpu: "{{ ansible_processor | select('match', 'Intel') | list }}"
    amd_cpu: "{{ ansible_processor | select('match', 'AMD') | list }}"

- name: "Abort if unknown cpu_type"
  ansible.builtin.fail:
    msg: "cpu-type not recognized"
  when: cpu_type == 'unknown'

