- name: "Install Intel/AMD CPU microcode-updates package"
  community.general.pacman:
    name: "{{ cpu_type }}-ucode"
    state: present

- name: "Set the ucode_updates_img_path play fact"
  ansible.builtin.set_fact:
    ucode_updates_img_path: "{{ boot_dir_path }}/{{ cpu_type }}-ucode.img"

