# - name: "Check if {{ cpu_microcode_grub_cfg_path }} exists"
#   stat:
#     path: "{{ cpu_microcode_grub_cfg_path }}"
#   register: grub_cfg_file

- name: "Abort if {{ cpu_microcode_grub_cfg_path }} file not found"
  fail:
    msg: "{{ cpu_microcode_grub_cfg_path }} file not found"
  # when: grub_cfg_file.stat.exists == false
  when: "{{ cpu_microcode_grub_cfg_path }}" is exists

- name: "Add grub.cfg variable for the microcode-updates image in /boot"
  lineinfile:
    path: "{{ cpu_microcode_grub_cfg_path }}"
    regexp: '^set ucode_updates='
    line: "set ucode_updates=\"{{ ucode_updates_img }}\""
    insertafter: '^# select initramfs to boot$'
    state: present
  vars:
    ucode_updates_img: "{{ cpu_microcode_boot_dir_path }}/{{ cpu_type }}-ucode.img"
  become: true
  become_user: root

- name: "Set grub.cfg to load microcode-updates image before initramfs"
  replace:
    path: "{{ cpu_microcode_grub_cfg_path }}"
    regexp: '^(\s*)initrd (\${\w+_initramfs})$'
    replace: '\1initrd ${ucode_updates} \2'
  become: true
  become_user: root

