- name: "Abort if {{ grub_cfg_file_path }} file not found"
  ansible.builtin.fail:
    msg: "{{ grub_cfg_file_path }} file not found"
  when: grub_cfg_file_path is not exists

- name: "Set grub.cfg to load microcode-updates image before initramfs"
  ansible.builtin.replace:
    path: "{{ grub_cfg_file_path }}"
    regexp: >-
      ^(\s*initrd)(\s+)(\S+)$
    replace: >-
      \1\2{{ ucode_updates_img_path }} \3
  become: true
  become_user: root

