- name: "Abort if {{ cpu_microcode_grub_cfg_path }} file not found"
  fail:
    msg: "{{ cpu_microcode_grub_cfg_path }} file not found"
  when: cpu_microcode_grub_cfg_path is not exists

- name: "Set grub.cfg to load microcode-updates image before initramfs"
  replace:
    path: "{{ cpu_microcode_grub_cfg_path }}"
    regexp: >-
      ^(\s*initrd)(\s+)(\S+)$
    replace: >-
      \1\2{{ ucode_updates_img }} \3
  vars:
    ucode_updates_img: "{{ cpu_microcode_boot_dir_path }}/{{ cpu_type }}-ucode.img"
  become: true
  become_user: root

