- name: "Determine CPU type (Intel, AMD, etc.)"
  include_tasks: get_cpu_type.yml

- name: "Install microcode-updates and load early (before initramfs) with GRUB"
  block:
    - name: "Check if {{ grub_cfg_path }} exists, indicating GRUB bootloader"
      stat:
        path: "{{ grub_cfg_path }}"
      register: grub_cfg_file
    - name: "Abort if GRUB bootloader not installed"
      fail:
        msg: "{{ grub_cfg_path }} not present: GRUB required to set up ucode"
      when: grub_cfg_file.stat.exists == false
    - name: "Install Intel/AMD CPU microcode-updates package"
      pacman:
        name: "{{ cpu_type }}-ucode"
        state: present
    - name: "Add grub.cfg variable for the microcode-updates image in /boot"
      lineinfile:
        path: "{{ grub_cfg_path }}"
        regexp: '^set ucode_updates='
        line: "set ucode_updates=\"{{ ucode_updates_img }}\""
        insertafter: '^# select initramfs to boot$'
        state: present
    - name: "Set grub.cfg to load microcode-updates image before initramfs"
      replace:
        path: "{{ grub_cfg_path }}"
        regexp: '^(\s*)initrd (\${\w+_initramfs})$'
        replace: '\1initrd ${ucode_updates} \2'
  vars:
    grub_cfg_path: "/boot/grub/grub.cfg"
    ucode_updates_img: "/ROOT/default/@/boot/{{ cpu_type }}-ucode.img"
  become: true
  become_user: root
  when: cpu_type != "unknown"

